config/routes.rb
Depot2::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :created
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    root 'store#index', as: 'store'
end

  

  
  

end

app/views/layouts/application.html.erb
	<!DOCTYPE html>
	<html>
	<head>
	  <meta charaset="utf-8">
	  <title>Depot2</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body class="<%= controller.controller_name %>">
		<div id="banner">
			<%= image_tag("logo.png") %>
			<%= @page_title || "Pragmatic Bookshelf" %>
		</div>
		<div id="columns">
			<div id="side">
				<!--<div id = "cart">
					<%= render @cart %>
				</div>-->
				<ul>
					<li><%= link_to("ホーム", store_path) %></li>
					<li><a href="">よくある質問</a></li>
					<li><a href="">ニュース</a></li>
					<li><a href="">お問い合わせ</a></li>
					<li id="dayline"><%= time_now.to_s %></li>
					<li id="dayline"><%= @time.to_s %></li>
					<%= puts "@cart = #{@cart}" %>
					<% if @cart %>
						<li><%= link_to("カート",(@cart)) %></li>
					<% end %>
				</ul>
				<% #if session[:user_id] %>
					<ul>
						<li><%= link_to '注文', orders_path %></li>
						<li><%= link_to '商品', products_path %></li>
						<li><%= link_to 'ユーザー', users_path %></li>
					</ul>
					<%= button_to 'ログアウト', logout_path, method: :delete %>
				<% #end %>
			</div>
		
			<div id="main">
				<%= yield %>
			</div>
		</div>
	</body>
	</html>